# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - method: poetry # ¡Correcto para un proyecto con Poetry y pyproject.toml!

sphinx:
  configuration: docs/conf.py # Asegúrate de que esta ruta sea correcta
