# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - method: poetry
      # We are temporarily removing the 'extras' key to simplify.
      # Poetry should still try to install dependencies from pyproject.toml,
      # including dependency groups if its default behavior includes them.

sphinx:
  configuration: docs/conf.py
